### ISSUE TITLE
Designのissue

### ISSUE THREAD

**Issue by rinaciel** [k1rn/k1rn.github.io#2]
- [x] top pageラフ画
- [x] top pageワイヤーフレーム
- [x] top page モックアップ
- [x] top pageモックアップをコーディングチームに送る
- [x] 個人pageラフ画
- [x] 個人pageワイヤーフレーム
- [x] 個人pageモックアップ
- [x] 個人pageモックアップをコーディングチームに送る

**Comment by enface** [comment]
- [x] プロフィール項目決め
- [x] タイトルロゴデザイン
